apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
data:
  msg_01: "Kubedev  -- CTRL+ALT+HALELUJAH "
  msg_02: "Kubedev  -- FAZ CERTO QUE DA CERTO "
  msg_03: "Kubedev  -- QUANTAS PALMAS SE FAZ UM VIDEO "
  msg_04: "Kubedev  -- K8S KUBERNETES. "
  msg_05: "Kubedev  -- ARGOCD - DEPLOY EM SEU CLUSTER. "
  

